"""First Migration

Revision ID: 87cce8283acd
Revises: 
Create Date: 2023-03-25 18:14:31.607858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cce8283acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URLS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=False),
    sa.Column('short_url', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URLS')
    # ### end Alembic commands ###
